modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="testmod"
version="1.0.0"
displayName="TestMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="MAx, MCreator"

[[dependencies.testmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




